export const PREPROD_CONTRACT_ADDRESS = localStorage.getItem('PREPROD_CONTRACT_ADDRESS') || 'UPDATE_WITH_YOUR_PREPROD_CONTRACT_ADDRESS';
export const MIN_GPA_THRESHOLD = 800; // 8.0 GPA scaled ×100
export const MAX_INCOME_THRESHOLD = 250000; // ₹2,50,000 INR
